#!/bin/zsh
help() {
  echo "$0 [-rm] [-a] dir"
  exit 1
}

MAXDEPTH=(-maxdepth 1)

while true;
do
  case "$1" in
    -- ) break ;;
    --rm|-rm ) shift; REMOVE=true ;;
    -a ) shift; MAXDEPTH=();;
    -h) help ;;
    *) break;;
  esac
done

find "$@" $MAXDEPTH -type l -print | while read TARGET; do 
    SRC=$(readlink ${TARGET})
    ( cd "$(dirname $TARGET)";
    if [[ ! -e $SRC ]]; then 
      if [[ -z $REMOVE ]]; then
        echo "BAD LINK: ${TARGET} -> ${SRC}"
      else
        echo "rm BAD LINK: ${TARGET} -> ${SRC}"
        rm "$(basename $TARGET)"
      fi
    fi 
    )
done
  
